[package]
name = "min_jwt"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "Minimal JSON Web Token library built on top of ring"
repository = "https://github.com/bluk/min_jwt"
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
ring = "0.16.9"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
