[package]
name = "min_jwt"
version = "0.2.0"
license = "MIT OR Apache-2.0"
description = "Minimal JSON Web Token library"
repository = "https://github.com/bluk/min_jwt"
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2018"
readme = "README.md"
include = [
  "src/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[dependencies]
base64 = "0.13.0"
p256 = { version = "0.9.0", optional = true, default-features = false, features = ["arithmetic", "ecdsa", "ecdsa-core", "jwk"] }
rsa = { version = "0.5.0", optional = true, default-features = false, features = ["alloc"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

regex = { version = "1", optional = true }

ring = { version = "0.16.20", optional = true }

wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3.55", optional = true }

[dependencies.web-sys]
version = "0.3.55"
optional = true
features = [
  'AbortSignal',
  'Crypto',
  'CryptoKey',
  'ServiceWorkerGlobalScope',
  'SubtleCrypto',
  'WorkerGlobalScope',
]

[dev-dependencies]
rand = { version = "0.8" }

[features]
default = ["p256", "rsa", "ring", "serde", "serde_json", "web_crypto"]

web_crypto = ["js-sys", "regex", "serde", "serde_json", "wasm-bindgen", "wasm-bindgen-futures", "web-sys"]