[package]
name = "min_jwt"
version = "0.2.0"
license = "MIT OR Apache-2.0"
description = "Minimal JSON Web Token library"
repository = "https://github.com/bluk/min_jwt"
authors = ["Bryant Luk <code@bryantluk.com>"]
edition = "2018"
readme = "README.md"
include = [
  "src/**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[dependencies]
base64 = "0.13.0"
ring = { version = "0.16.20", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = ["ring", "serde", "serde_json"]