name: Rust CI

permissions:
  contents: read

on:
  push:

  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - stable
          - 1.65.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust Version
        run: rustc --version
      - run: cargo build --release --no-default-features --features alloc
      - run: cargo build --release --no-default-features --features alloc,p256
      - run: cargo build --release --no-default-features --features alloc,rsa,sha2,signature
      - run: cargo build --release --no-default-features --features alloc,ring
      - run: cargo build --release --no-default-features --features alloc,p256,serde,serde_json
      - run: cargo build --release --no-default-features --features alloc,rsa,sha2,serde,serde_json,signature
      - run: cargo build --release --no-default-features --features alloc,ring,serde,serde_json
      - run: cargo build --release --no-default-features --features alloc,ring,p256,serde,serde_json
      - run: cargo build --release --no-default-features --features alloc,ring,rsa,sha2,serde,serde_json,signature
      - run: cargo build --release --no-default-features --features std
      - run: cargo build --release --no-default-features --features std,p256
      - run: cargo build --release --no-default-features --features std,rsa,sha2,signature
      - run: cargo build --release --no-default-features --features std,ring
      - run: cargo build --release --no-default-features --features std,p256,serde,serde_json
      - run: cargo build --release --no-default-features --features std,rsa,sha2,serde,serde_json,signature
      - run: cargo build --release --no-default-features --features std,ring,serde,serde_json
      - run: cargo build --release --no-default-features --features std,ring,p256,serde,serde_json
      - run: cargo build --release --no-default-features --features std,ring,rsa,sha2,serde,serde_json,signature
      - run: cargo build --release --all-features
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - stable
          - 1.65.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust Version
        run: rustc --version
      - run: cargo check --all-features
      - run: cargo test --no-default-features --features alloc
      - run: cargo test --no-default-features --features std
      - run: cargo test
      - run: cargo test --all-features
  rustfmt:
    name: Format
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    container: rust
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - name: Rust Version
        run: rustc --version
      - run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    container: rust
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo clippy --all-features --all-targets